### ISSUE TITLE
Validate location end changes wrt parents/children

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#111]
Need to determine e.g. if you change the end of an exon, how that might affect the end of the mRNA and gene. Initial thought is that if you are extending an exon past the end of the mRNA/gene, then the change object must have changes for all three (exon, mRNA, gene) together.

Also need to determine if there is a general-case rule regarding if parents are allowed to extend past children.

Will fill this out with more detail after more research.

**Comment by kyostiebi** [comment]
Ready for the first test. I also added check that child's start position cannot be less than parent't start position.
