### ISSUE TITLE
Add DeleteFeatureChange

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#128]
Given a feature ID, the `DeleteFeatureChange` change should delete the feature and all its children in the plugin and in the database (i.e. has both `applyToClient` and `applyToServer` methods).

(Note: since `applyToClient` will likely change soon since the data store is being moved from the ApolloView to the session, the first version of this can leave a TODO stub in `applyToClient`.)

Also will need to update the `featureIds` array of the top-level feature in the database with the `applyToServer` method.

Also, the `getInverse` of `CopyFeatureChange` should be updated to supply a `DeleteFeatureChange` (the current `getInverse` looks like it's broken).

For the first version of the `DeleteFeatureChange` change, the `getInverse` will not work, since we need `AddFeatureChange` for that, which doesn't exist yet.

**Comment by kyostiebi** [comment]
If we are deleting feature that has parent feature, should we also update parent's start or end position if needed? For example if deleted sub-feature had the smallest start position among other sub-features.

**Comment by garrettjstevens** [comment]
Here's a summary of the problem we're having with undoing deleting features. @rbuels, let us know if you have any input.

To undo a delete feature, the DeleteFeatureChange must have a record that what the feature looked like and possibly what its parent feature was. That way the undo knows what/where to add back. This means that either one of two things must happen:

1. The frontend must send not only the deleted feature's ID, but its whole structure to the backend
- OR
2. The frontend sends just the feature ID to delete, and the backend adds the feature's structure to the serialized change before it's written to the changelog

The problem with (1) is that the frontend doesn't keep track of what the features look like on the backend. When it fetches the features, they are loaded into the state tree. We'd either have to keep some record of the original feature response on the state tree, or have a very robust way of translating the feature from the state tree format back into a MongoDB document format

The problem with (2) is that currently we assume that when the change is initially created, it has all the information it needs. We'd have to find some way of getting an "updated change serialization" from the backend when submitting a change. That way the change on the "undo stack" in the frontend has the information it needs.

**Comment by cmdcolin** [comment]
this is perhaps a big change to the current system but what if the system used snapshots of the feature for patch based change tracking? the jbrowse 2 undo/redo system ended up adopting snapshots and it seemed like it was pretty easy to integrate

**Comment by garrettjstevens** [comment]
snapshots might work on the front end. On the back end we'll have to see if there's something in MongoDB to make it easy to do.
