### ISSUE TITLE
Add Google Authentication using NestJS passport

### ISSUE THREAD

**Issue by kyostiebi** [GMOD/Apollo3#148]
Add Google Authentication using NestJS passport. Once authentication against Google has been done successfully then
1. If user is very first user in Mongo (in _users_ -collection) then add _admin_ role to the new user; otherwise add the new user into Mongo (_users_ -collection) using default role as defined in property file. The following information should be saved into Mongo: username, email and role.
2. Google access token should be changed to Apollo token where payload contains username and roles.

**Comment by garrettjstevens** [comment]
Done in #159
