### ISSUE TITLE
Reads from BAM displayed within split-reads

### ISSUE THREAD

**Issue by mberriman** [GMOD/Apollo3#151]
There is a display bug in the Apollo 2 that would be good to fix in Apollo 3.  Where individual read alignments contain long splits, other reads from the BAM are often displayed over the split.  This makes it difficult to visually connect the read segments.  In attached screenshot most of the split reads are off the screen.   But many of the intact red-reads have been place on the lines representing splits, rather than drawn in the white space below.

![Screenshot 2022-10-24 at 11 44 11](https://user-images.githubusercontent.com/22172377/197508754-784ba6e2-0c8a-46f2-bb2b-23dfd45c4656.png)

**Comment by garrettjstevens** [comment]
@mberriman looks like this is a bug in JBrowse 1. I'd guess it's fixed in JBrowse 2, but if you can send me a BAM snippet that displays the behavior I'd be happy to check.
