### ISSUE TITLE
Add increment to Changes collection

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#152]
We probably can't use one of the existing mongoose plugins to auto-increment, since they aren't flexible enough for us, but we can do it on our own.

- Add a collection that stores the current value of the counter.
  - Some examples can be found [here](https://www.mongodb.com/basics/mongodb-auto-increment) and [here](https://medium.com/@yallaling001/how-to-insert-auto-increment-number-in-mongodb-33b6b03abb89) (under "Creating a custom auto-increment")
  - The schema will be in `packages/apollo-schemas/src`
  - The schema will be imported and registered in `packages/apollo-collaboration-server/src/changes/changes.module.ts`
- Add logic in `packages/apollo-collaboration-server/src/changes/changes.service.ts` before `this.changeModel.create` to add the correct sequence number to the `changeEntry`
  - The changes schema will have to be updated to have this field as well.
  - For now, this will involve doing a `findOneAndUpdate` or `findAndModify` to get and increment the sequence number from the new collection. Eventually this may be swapped out with e.g. a `fetch` to an API to get the sequence number.

**Comment by haessar** [comment]
This is now ready for review https://github.com/GMOD/Apollo3/pull/156
