### ISSUE TITLE
Add correct user information to changelog

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#157]
In the backend, get the token that the user passed when submitting the change and decode the user from that token. Then in the /changes POST endpoint when creating a new change in the MongoDB change collection, add the user's username to the change document.

**Comment by kyostiebi** [comment]
Logic is done in _ChangeInterceptor_ -class. Username is added if _user_ -property is not filled in UI.

**Comment by garrettjstevens** [comment]
Donein #160
