### ISSUE TITLE
Echo user locations over websockets

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#166]
When a user opens a particular area in an Apollo track, or navigates around an Apollo track, the client will send the current area (possible debounced) to the collaboration server.

The server will then echo that location to all other clients (not storing it anywhere).

Also, when a user first logs in, it will send a message to the collaboration server that is echoed out, and all other clients will then send their current locations so the new user can get its record of where other users are initialized.

**Comment by rbuels** [comment]
This sounds like a good design. We will see if the re-echoing on login
results in too much message traffic. If it does, we can store last known
locations on the server. But we probably don’t need to worry about that
yet.

**Comment by garrettjstevens** [comment]
Partially done in #170, still need the initialization portion.

**Comment by kyostiebi** [comment]
I guess we also need to indicate other users when closing track. Otherwise the last working region is still shown

**Comment by garrettjstevens** [comment]
True. Also, similarly, we should detect when the user closes the browser window, maybe with [`beforeUnload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event).

**Comment by garrettjstevens** [comment]
Currently in the `autorun` inside the `afterCreate` in `src/session.ts`, each location is sent separately as a single call to the `/userLocation` endpoint, and then each client gets the echoed location and adds it to its current locations.

In order to be able to send a signal showing that a view has closed, we should change the `/userLocation` endpoint to take an array of locations, and inside the `autorun` we send an array of locations that represents all of the locations currently open. That way if a view is closed, the array will be shorter, and the clients will reflect that. If an empty array is sent, that means the user has closed all views (or closed the browser window). When this location is echoed out by the server websocket, it will also be as an array of locations, not a single location. This will also mean that the `addOrUpdateCollaborator` action in `src/session.ts` should replace all existing locations instead of adding to them.

**Comment by garrettjstevens** [comment]
As for calling the endpoint that requests other users to broadcast their location, that should happen in the `initialize` action of `src/ApolloInternetAccount/model.ts`, after `self.addSocketListeners`.

When the client receives a request to broadcast its location, it calls `session.broadcastLocations`, which will be a new action that will have to be factored out of the code currently in the `autorun`.

**Comment by garrettjstevens** [comment]
Also in the `initialize` action, we'll need to listen for the browser window to close with something like
```
window.addEventListener('beforeunload', () => {
  self.postUserLocations([])
})
```
