### ISSUE TITLE
Store and query ontologies

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#177]
Starting with the [Sequence Ontology](http://www.sequenceontology.org/), we need to be able to store an ontology and retrieve info from it.

For this first version, data input should be in OBO or OWL format. A common example of what we will have to query is when adding a child feature, we need to query which feature types are a "member_of" (and all that type's "is_a"s) the parent type. A couple options for this:

- Load data into in-memory triple store on the server and use SPARQL query to query it
- Load data into MongoDB and use MongoDB's [`$graphLookup`](https://www.mongodb.com/databases/mongodb-graph-database) to query it
- Pre-process the data, finding all possible "member_of"s for all terms, then load the processed data into MongoDB. (This won't work well if we want to do other types of queries against the ontology)

**Comment by garrettjstevens** [comment]
An OBO parser we could use to load OBO files into MongoDB: https://github.com/bionode/bionode-obo

**Comment by garrettjstevens** [comment]
Simple OBO file to start with: https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/master/Ontology_Files/so-simple.obo

**Comment by kyostiebi** [comment]
All OBO parsers (written Javascript / Typescript) I was able to found were deprecated or their dependencies were deprecated or libraries were already removed from package libraries. In order to move on, I used Java based ROBOT (http://robot.obolibrary.org/) command line tool to convert OBO to OBO Graph JSON. The converted file I loaded into new "edges" and "nodes" collections in Mongo.

**Comment by garrettjstevens** [comment]
Turns out there are three terms we need to look for to find parent relationships: "part_of", which is the one mentioned in the GFF3 spec, and also "member_of" and "integral_part_of", which are its two subtypes.

Source: http://sequenceontology.org/browser/current_release/term/part_of
![](http://sequenceontology.org/img/dag_gif/current_release/part_of_sm.png)
