### ISSUE TITLE
Investigate assembly loading timeouts

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#195]
Currently in `app.module.ts` when registering the Mongoose module, we set a large `maxTimeMS`, since that seems to fix some issues people have had loading large data sets. We want to avoid this if we can, though. It's possible that the timeouts are coming from loading the chunks of the reference sequences. We need to:

- Test loading some large assemblies with and without annotations and without setting `maxTimeMS` to see if we can determine where the timeouts are happening.
- See if reducing the default chunk size (set in `refSeq.schema.ts`) makes it so those can be loaded without increasing `maxTimeMS`

**Comment by cmdcolin** [comment]
I don't recall if there were particular reasons for having the sequence in the database, but if not, could be worth considering storing externally. I believe I made a comment about this a long while back, but it could be worth re-considering potentially(?)

**Comment by garrettjstevens** [comment]
As part of the requirements for bringing Artemis features to Apollo 3, the sequence has to be editable, which is why we're storing it in the database. There could potentially be a mode for those who don't care about sequence editing, though, that uses an external sequence to simplify things.

**Comment by cmdcolin** [comment]
It may not necessarily be the case that applying a sequence change requires storing in the database. Apollo1 had the concept of sequence changes also, stored just as patches in a database table. 

I will also note, editing the sequence can be a very challenging feature to deliver correctly, and I would seriously consider what things can be done to try to simplify it or even define the problem away

**Comment by garrettjstevens** [comment]
These timeouts don't seem to happen any more.
