### ISSUE TITLE
Organism access dropdown menu redesign

### ISSUE THREAD

**Issue by obsidian83** [GMOD/Apollo3#2]
For VEuPathDB we have over 400 organisms that will be loaded eventually into our Apollo instance.

Switching between organisms via both the jbrowse menu and annotator tab menus with an exhaustive list of organisms makes it difficult to find the desired one. 

<img width="1861" alt="Screenshot 2020-11-30 at 14 29 37" src="https://user-images.githubusercontent.com/10411470/100626454-bd6c6d80-331d-11eb-9e31-e35c4d08dff6.png">

I propose a more faceted menu, with a tree like structure, for either or both menus. 

<img width="1893" alt="Screenshot 2020-11-30 at 15 08 04" src="https://user-images.githubusercontent.com/10411470/100626576-e987ee80-331d-11eb-94fa-f720185545d5.png">

**Comment by nathandunn** [comment]
@obsidian83  I did a small implementation https://github.com/GMOD/Apollo/pull/2537 adding genus, species, etc. to the names and sorting appropriately.

However, we are going to be implementing a react component that does a lot of the same stuff.   Ultimately I want something that looks like the current track list (or faceted browser), but we'll have a lot more control in the newer stack (in this repo).

**Comment by garrettjstevens** [comment]
Species selection in Apollo 3 is handled completely by JBrowse 2. Some sort of hierarchical selector could be possible, but would probably need to be implemented as a JBrowse plugin.
