### ISSUE TITLE
GFF3 data export throws exception after adding a sub-feature

### ISSUE THREAD

**Issue by kyostiebi** [GMOD/Apollo3#204]
To re-produce:

1. Add new assembly. I used **_Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.109.primary_assembly.29.fa_** and **_Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.109.primary_assembly.29.gff3_** that can be found here: https://www.ensembl.org/info/data/ftp/index.html
2. In my case, I added a new sub-feature which type was **_exon_region_** to existing **_exon_** which start is 69796 and end is 73033.
3. I exported the assembly (GFF3), OK.
4. I opened the exon's "_**Modify feature attribute**_" -modal window from context menu. Without making any modification, I pressed "_**Submit changes**_"
5. I tried to export the assembly again
-->
[Nest] 18341  - 05/02/2023, 4:41:06 PM   ERROR [FeaturesService] GFF3 export failed
[Nest] 18341  - 05/02/2023, 4:41:06 PM   ERROR [FeaturesService] TypeError: Cannot read properties of undefined (reading '0')
[Nest] 18341  - 05/02/2023, 4:41:06 PM   ERROR [ExpressAdapter] Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at /Users/kyosti/src/Apollo/jbrowse-plugin-apollo/packages/apollo-collaboration-server/src/features/features.service.ts:109:56
    at Array.map (<anonymous>)
    at /Users/kyosti/src/Apollo/jbrowse-plugin-apollo/packages/apollo-collaboration-server/src/features/features.service.ts:108:49
    at Array.map (<anonymous>)
    at makeGFF3Feature (/Users/kyosti/src/Apollo/jbrowse-plugin-apollo/packages/apollo-collaboration-server/src/features/features.service.ts:85:20)
    at /Users/kyosti/src/Apollo/jbrowse-plugin-apollo/packages/apollo-collaboration-server/src/features/features.service.ts:109:11
    at Array.map (<anonymous>)
    at /Users/kyosti/src/Apollo/jbrowse-plugin-apollo/packages/apollo-collaboration-server/src/features/features.service.ts:108:49
    at Array.map (<anonymous>)
    at makeGFF3Feature (/Users/kyosti/src/Apollo/jbrowse-plugin-apollo/packages/apollo-collaboration-server/src/features/features.service.ts:85:20)

**Comment by rbuels** [comment]
direct download links:

https://ftp.ensembl.org/pub/release-109/fasta/gallus_gallus/dna/Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.dna.primary_assembly.29.fa.gz
https://ftp.ensembl.org/pub/release-109/gff3/gallus_gallus/Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.109.primary_assembly.29.gff3.gz

**Comment by rbuels** [comment]
I have been trying to reproduce this and have not been able to. I've tried the steps above, and the GFF3 export has been succeeding.

**Comment by kyostiebi** [comment]
Please, see screen recording that I just created using **_main_** -branch. Video can be found here: https://drive.google.com/drive/folders/1JFF4eYMo-qg47fkigO73HdIBZKqvAsJ_?usp=share_link

**Comment by rbuels** [comment]
ok I was able to reproduce it with that, thanks.
