### ISSUE TITLE
Add mouse handling to customizable glyphs

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#208]
This will start from the dynamic_blocks_rendering branch

There is currently an abstract Glyph class (`packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/glyphs/Glyph.ts`) that has `draw`, `getRowCount` and `getFeatureFromLayout` methods.

The glyph needs some way of reacting to mouse events, though. Currently the mouse handlers are defined in `packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel.ts`, and there's state e.g. `apolloFeatureUnderMouse`, and then an autorun that watches that state and reacts to it (by e.g. drawing a mouseover highlight). Instead of drawing a mouseover highlight from the stateModel, though, we might need to keep not only the feature under the mouse, but the x and y positions, too, and then pass these into some method on the glyph and have it decide whether to draw something.

Specifically, the `'LinearApolloDisplayRenderMouseoverAndDrag'` autorun should be updated to call the glyph instead of drawing directly.

The actual canvases being rendered to are here: `packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/LinearApolloDisplay.tsx`

Currently the only implemented glyph is the BoxGlyph, where every feature is only one line and subfeatures are not rendered.

**Comment by rbuels** [comment]
completed by #211
