### ISSUE TITLE
Improve open/close/sizing behavior of details view

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#220]
Split off from some parts of #216

In `packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/rendering.ts` there is a prop `detailsMinHeight`, a getter `featuresHeight` based on the layout, and a getter `detailsHeight`, based on `detailsMinHeight`, `featuresHeight`, and `height`, which is a getter in `packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/trackHeightMixin.ts`. These, along with `apolloSelectedFeature` in `packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/stateModel/base.ts`, determine whether the details panel is visible and how big it is.

We could change the behavior of the details panel. We could do something more like Artemis, where the details panel shows a scrollable list of features in the view, and the row corresponding to the selected feature is highlighted in the list. In this case, the details would probably only have two state, open and closed, which would be set by the user, and selecting features wouldn't automatically open the details.

![image](https://github.com/GMOD/Apollo3/assets/25592344/03f9bccd-519a-41c4-8804-8b0b9c8424bb)

If we keep something more like the current behavior, it might be good to increase the overall height of the display when the details are opened instead of opening the details in the existing height, since the current behavior can lead to the selected feature getting covered by the details when they open.

We could also probably use a drag handle between the details and the linear display for easier resizing.

**Comment by rbuels** [comment]
Discussions with @garrettjstevens yesterday:

- change the details panel to be a tabular view of all the features in the currently displayed area. If a feature is selected, the selections are synced between the glyphs and tabular displays
- make sure that clicking a feature doesn't hide it behind the tabular panel
- tabular display should be much more compact

Implementation phases:
- make it have a resize handle and be collapsible
- work on the editing component after that

**Comment by rbuels** [comment]
notes from more discussions with @garrettjstevens

desired features for the editing component:
* hybrid of data grid and tree list. top-level features expandable/collapsible to view children
* right-clicking on a feature brings up the same menu as right-clicking the glyph above
* cutting and pasting behavior is going to take some experimentation to get right
