### ISSUE TITLE
Apollo Search Adapter

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#230]
We'll need an Apollo search adapter so that users can search in the JBrowse search box and get results provided by the Apollo Collaboration Server.

We can use the [TrixTextSearchAdapter](https://github.com/GMOD/jbrowse-components/blob/0dfd9bfe2232df769fdd17b571693afd95afc701/plugins/trix/src/index.ts) as a model.

To be determined: what do we want to search? All attributes for every feature and subfeature? Full or prefix search?

We also need to investigate if our MongoDB schema for Features needs any more indices to make this performant.

**Comment by kyostiebi** [comment]
When searched text is found inside a sub-document (for example in child feature) what should be returned from backend to UI? Should backend return a) only the found text/field value, b) the sub-document, c) the whole document with all possible sub-documents or d) something else?

**Comment by garrettjstevens** [comment]
> When searched text is found inside a sub-document (for example in child feature) what should be returned from backend to UI? Should backend return a) only the found text/field value, b) the sub-document, c) the whole document with all possible sub-documents or d) something else?

@dariober and I discussed today, and we decided (b).

Also, @dariober, as you're exploring searching inside child features as we talked about, you could try a [wildcard text index](https://www.mongodb.com/docs/manual/core/index-text/#wildcard-text-indexes) on the features collection and then use the `$text` operator to search like described [here](https://www.mongodb.com/docs/manual/core/link-text-indexes/).

**Comment by dariober** [comment]
In file [tmp/mongodb/searchGff.mongo](https://github.com/GMOD/Apollo3/blob/mongodb-query/tmp/mongodb/searchGff.mongo) of branch [mongodb-query](https://github.com/GMOD/Apollo3/tree/mongodb-query) I put a stub for querying mongodb. 

I *think* it behaves correctly in terms of recursively searching and returning sub-documents matching a query, but I need to better test it. I drop it here in case you want to have a preview. For now, it only searches all the attribute values for either a full match or a match as a regular expression. 

I'm not using indexes just now so it may be prohibitively slow.
