### ISSUE TITLE
Make subfeatures selectable in gene glyphs

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#247]
In `CanonicalGeneGlyph` and `ImplicitExonGeneGlyph`, the `getFeatureFromLayout` method needs to be modified to return the subfeature for the specified position, not the top-level feature. An example of this works can be seen in `GenericChildGlyph`.

**Comment by shashankbrgowda** [comment]
@garrettjstevens @rbuels Few questions on this
1. Parent feature (gene) is not rendered in ImplicitExonGeneGlyph So, what to do with grey shadow to highlight all the features under it ?
2. On hover of a feature (CDS/UTR) its highlights all the features under parent feature(gene), what to do with this ?

Created a draft pr for this https://github.com/GMOD/Apollo3/pull/249 while feature select works fine not sure whether this is what you're expecting

![image](https://github.com/GMOD/Apollo3/assets/13611226/c64bd528-e8ef-41ca-8a69-16d2f81d8900)

**Comment by garrettjstevens** [comment]
1. For now let's say the gene is not selectable in the track and see how that feels
2. Not sure what you mean
3. For now we'll say that only things that exist in that specific GFF3 can be selected. So if there is no UTR, you can't select it in the glyph.
4. You can look at the canonical gene example GFF3 in [the spec](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md#the-canonical-gene). It has for example four CDS with the ID cds00001, which means that in our code there is one feature (cds00001) with four discontinuous locations. Here's an example GFF3 you can use in testing:
```
##gff-version 3.1.26
ctgA	.	gene	1000	9000	.	+	.	ID=gene00001;Name=EDEN
ctgA	.	mRNA	1050	9000	.	+	.	ID=mRNA00001;Parent=gene00001
ctgA	.	mRNA	1050	9000	.	+	.	ID=mRNA00002;Parent=gene00001
ctgA	.	mRNA	1300	9000	.	+	.	ID=mRNA00003;Parent=gene00001
ctgA	.	exon	1300	1500	.	+	.	Parent=mRNA00003
ctgA	.	exon	1050	1500	.	+	.	Parent=mRNA00001,mRNA00002
ctgA	.	exon	3000	3902	.	+	.	Parent=mRNA00001,mRNA00003
ctgA	.	exon	5000	5500	.	+	.	Parent=mRNA00001,mRNA00002,mRNA00003
ctgA	.	exon	7000	9000	.	+	.	Parent=mRNA00001,mRNA00002,mRNA00003
ctgA	.	CDS	1201	1500	.	+	0	ID=cds00001;Parent=mRNA00001
ctgA	.	CDS	3000	3902	.	+	0	ID=cds00001;Parent=mRNA00001
ctgA	.	CDS	5000	5500	.	+	0	ID=cds00001;Parent=mRNA00001
ctgA	.	CDS	7000	7600	.	+	0	ID=cds00001;Parent=mRNA00001
ctgA	.	CDS	1201	1500	.	+	0	ID=cds00002;Parent=mRNA00002
ctgA	.	CDS	5000	5500	.	+	0	ID=cds00002;Parent=mRNA00002
ctgA	.	CDS	7000	7600	.	+	0	ID=cds00002;Parent=mRNA00002
ctgA	.	CDS	3301	3902	.	+	0	ID=cds00003;Parent=mRNA00003
ctgA	.	CDS	5000	5500	.	+	1	ID=cds00003;Parent=mRNA00003
ctgA	.	CDS	7000	7600	.	+	1	ID=cds00003;Parent=mRNA00003
ctgA	.	CDS	3391	3902	.	+	0	ID=cds00004;Parent=mRNA00003
ctgA	.	CDS	5000	5500	.	+	1	ID=cds00004;Parent=mRNA00003
ctgA	.	CDS	7000	7600	.	+	1	ID=cds00004;Parent=mRNA00003
```
