### ISSUE TITLE
Open local file on JBrowse desktop

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#254]
- In `OpenLocalFile.tsx`, check `isElectron` and add the following new behavior on desktop
- Don't read and parse the file, instead add the filename to the sequence metadata
- Create a new backend driver called `DesktopFileDriver`, similar to `InMemoryFileDriver` and `CollaborationServerDriver`.
- In `getBackendDriver` in `ClientDataStore`, check the sequence metadata, and if a filename exists, return `self.desktopFileDriver`.
- In `DesktopFileDriver`'s `getFeatures`, use the assembly name in the `Region` to get the assembly from the `assemblyManager`, then read that assembly's metadata to get its filename. Then read the file with `fs`, parse the features with `gff.parseStringSync`, convert to an Apollo feature (see `createFeature` in `OpenLocalFile`), and return the features filtered by the range in `Region`.
- Similar for `getSequence`, but use `gff.parseStringSync` with all options false except `parseSequence`, then get the sequence requested in `Region` and return it.

**Comment by kyostiebi** [comment]
In order to make features visible on the track, needed to comment the following code block (staring from line 74) in JBrowseDesktop TrackMenu.ts
_**...(supportedIndexingAdapters(trackSnapshot.adapter.type)**_

**Comment by garrettjstevens** [comment]
> In order to make features visible on the track, needed to comment the following code block (staring from line 74) in JBrowseDesktop TrackMenu.ts
> _**...(supportedIndexingAdapters(trackSnapshot.adapter.type)**_

https://github.com/GMOD/jbrowse-components/pull/3888 opened to fix this.

**Comment by kyostiebi** [comment]
After user has changed features, the features and sequences (from client data store) must be written back to original file. Parse also original file comments (if any) and sequence descriptions and write those back too.

**Comment by garrettjstevens** [comment]
Done in #272
