### ISSUE TITLE
Better demo data

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#260]
We need some data to demo the capabilities of Apollo on a real organism
- Something small (so we can also demo local editing)
- Annotations and sequence
- Evidence tracks (rna seq would be especially nice)

**Comment by dariober** [comment]
A couple of *Plasmodium* species should work well for this, for example *P. falciparum* and *P. chabaudi*. [PlasmoDB](https://plasmodb.org/plasmo/app/) has a number of resources. To get genomes and annotations:

```
curl -O https://plasmodb.org/common/downloads/release-64/Pfalciparum3D7/fasta/data/PlasmoDB-64_Pfalciparum3D7_Genome.fasta
curl -O https://plasmodb.org/common/downloads/release-64/Pfalciparum3D7/gff/data/PlasmoDB-64_Pfalciparum3D7.gff

curl -O https://plasmodb.org/common/downloads/release-64/Pchabaudichabaudi/fasta/data/PlasmoDB-64_Pchabaudichabaudi_Genome.fasta
curl -O https://plasmodb.org/common/downloads/release-64/Pchabaudichabaudi/gff/data/PlasmoDB-64_Pchabaudichabaudi.gff
```

Genome size is in the order of ~20 MB, but we can select a single chromosome to make it smaller.

For RNAseq, PlasmoDB has several links to public datasets. We may need to align the raw reads ourselves to get bam  and bigwig files but this is not a problem.

For comparing species, we can generate pairwise, "crunch" files. For example, considering one chromsome pair:

```
samtools faidx PlasmoDB-64_Pfalciparum3D7_Genome.fasta Pf3D7_06_v3 > PlasmoDB-64_Pfalciparum3D7_Pf3D7_06_v3.fasta
samtools faidx PlasmoDB-64_Pchabaudichabaudi_Genome.fasta PCHAS_01_v3 > PlasmoDB-64_Pchabaudichabaudi_PCHAS_01_v3.fasta

makeblastdb -in PlasmoDB-64_Pfalciparum3D7_Pf3D7_06_v3.fasta -dbtype nucl

sbatch -t 7-00:00:00 -e err.log -o out.log --wrap "
    tblastx -query PlasmoDB-64_Pchabaudichabaudi_PCHAS_01_v3.fasta \
           -db PlasmoDB-64_Pfalciparum3D7_Pf3D7_06_v3.fasta \
           -evalue 0.1 \
           -max_target_seqs 10 \
           -outfmt 6 > PCHAS_01_v3_vs_Pf3D7_06_v3.crunch"
```

(NB: The above takes around three days to complete, for larger chromosomes consider splitting the query in chunks).

**Comment by garrettjstevens** [comment]
@dariober could you provide an example of raw reads in a public dataset (with a link) for each of those to species? Thanks!
