### ISSUE TITLE
Add click and drag to gene glyphs

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#263]
Here are the actions that clicking and dragging should take in a gene glyph:

![Untitled drawing (1)](https://github.com/GMOD/Apollo3/assets/25592344/cdb5d135-4c8b-4a46-a606-f465004f4968)

Canonical Gene Glyph:
- 1 and 10: Don't implement for now
- 2 and 9: Change CDS
- 3 through 8: Change CDS and exon

Implicit Exon Gene Glyph
- 1 and 10: Don't implement for now
- 2 and 9: Change UTR and CDS
- 3 through 8: Change CDS

**Comment by shashankbrgowda** [comment]
Thanks @garrettjstevens. I have few questions

1. Can there be overlapping CDS/exon in Implicit Exon Gene Glyph ? When we're dragging CDSfrom 3 towards 8, should we limit it until 4  ?
2.  In Canonical gene glyph, when we drag CDS from 3 towards 8, Should We merge the discontinuous locations If they overlap ?
3. If exons coord is within CDS coord, its hidden under the CDS, How to handle this ?

**Comment by shashankbrgowda** [comment]
4. "2 and 9: Change UTR and CDS" -> does this mean when we drag CDS from 2 to 3, we need to increase the length of UTR ?

**Comment by garrettjstevens** [comment]
1. Limit it so it can't past 4. Going further would mean merging them, which we will work on later.
2. Also limit this here so they can't be dragged far enough to merge.
3. The exon and CDS should have the same coordinates, so when the CDS is dragged, update the exon to match.
4. Yes, increase the UTR so that its end matches the new position of 2.

**Comment by shashankbrgowda** [comment]
For Canonical Gene Glyph - If we drag the UTR from 9 towards 7 and beyond, should we delete the CDS ? or should we limit it ?

**Comment by cmdcolin** [comment]
is there any way to unify the two 'glyph models'? e.g. on import, just convert the data model to one representation. i'm not that familiar with the discussion but it seems like it will add code complexity to keep them differentiated

**Comment by garrettjstevens** [comment]
@shashankbrgowda let's limit it so that it has to be at least 1 bp.

@cmdcolin some people need one type of gene representation and some need the other in the GFF3 that Apollo exports. Once we have better exporting we might be able to convert to a single format internally.
