### ISSUE TITLE
Add initial server-side checks for CDS features

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#285]
- This check will be run only on the server side when features are requested. This logic will be factored out into a more general check class later.
- When features are requested
  - Check to see that the "StopCodonCheckReport" for each feature has a newer timestamp than the feature's last modified time stamp.
  - If not, run the StopCodonCheck, add the CheckReport for it, and then return the features

The StopCodonCheck should check for the following items:

- Make sure there are no stop codons inside any of the feature's CDSs.
  - Stop codons are TAA, TAG, or TGA
  - Make sure to take the reading frame into account, i.e. count only groups of three bases starting at the beginning of the CDS.
    - e.g. if the sequence was ATGATATGAAACTGA, this has an internal stop codon: ATG_ATA_**TGA**_AAC_TGA
    - This does not have an internal stop codon, even though it contains the sequence TGA internally, because it is not in the reading frame ATGATTGAACACTGA, ATG_ATT_GAA_CAC_TGA
- Make sure the last three bases of the CDS are a stop codon
  - If the length of the CDS is not a multiple of three, this check automatically fails
- If a mRNA has multiple CDS children (not a canonical gene representation, but fairly common), make sure to combine all the CDSs before doing this check.
- If the feature in on the negative strand, check the reverse complement of the CDS instead of the forward sequence.

**Comment by kyostiebi** [comment]
General question. If a feature has been updated since last time checkReports were run --> need to re-run checkReports. This is clear. But should we overwrite the old checkReport documents or should we create new documents every time when checkReports are run?

**Comment by kyostiebi** [comment]
As agreed with Garrett, if a feature is changed and there is need to re-run the check reports then simply delete old reports and create new ones. No need to save old reports.

**Comment by kyostiebi** [comment]
Add also check report to find possibly overlapping CDSs

**Comment by garrettjstevens** [comment]
Done in #312
