### ISSUE TITLE
Unable to add whole human assembly (fasta)

### ISSUE THREAD

**Issue by kyostiebi** [GMOD/Apollo3#295]
For reason or another, I can add for example human chr1, whole chicken assembly etc. but when I try to add whole human fasta, nothing happens until I get the attached error message (about after 6 mins). Before summer leave, I was able to add same whole human fasta without any issue.
![Screenshot 2023-10-04 at 10 19 29](https://github.com/GMOD/Apollo3/assets/88434919/5b3e1568-7c81-4d02-873f-5235867566a2)

**Comment by garrettjstevens** [comment]
Confirmed that this happens on my computer as well.

**Comment by garrettjstevens** [comment]
I've been trying to wrap my head around why the fix in #296 works, and I'm still not sure, but I figured out a couple things:

- Without the bug fix, the file transfer does actually start, you just can't tell from the network tab in the browser (that's how multi-part forms work, I guess)
- The compression stream and write stream both work fine for a while
- Then the file on disk stops getting bigger, but I can see the file hash still updating
- Eventually the file hash stops, too, but it doesn't ever show that it's finished, so eventually NestJS kills the inactive connection
