### ISSUE TITLE
BAM reads only highlight at the ends

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo3#3]
From:

https://groups.google.com/a/lbl.gov/forum/#!topic/apollo/X3QGLTgVfeU

When an annotated exon is highlighted only the BAM start or END is highlighted:

![image](https://user-images.githubusercontent.com/751274/78057679-f93cd680-733b-11ea-9d65-d655d4f0fa7b.png)

**Comment by nathandunn** [comment]
This will need to be addressed in JB2

**Comment by garrettjstevens** [comment]
See #439 for Apollo3/JB2 equivalent feature request.
