### ISSUE TITLE
Render check results on the LinearApolloDisplay

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#307]
Using the branch [add_check_initial](https://github.com/GMOD/Apollo3/tree/add_check_initial), render the contents of the checkResults (stored in the client data store) in the LinearApolloDisplay. As a first pass, we could do some small symbol at the beginning of the glyph with a tooltip with check info.

**Comment by garrettjstevens** [comment]
@dariober as discussed earlier today, I've started this in a branch here: [render_check_in_track](https://github.com/GMOD/Apollo3/tree/render_check_in_track)

The rendering is very rough, feel free to change anything you feel like. The biggest thing I think it still needs, though, is a tooltip that describes to the user what the warning is. You should be able to use the `Tooltip` component to do this. Here's an example of another place `Tooltip` is used in our codebase:

https://github.com/GMOD/Apollo3/blob/0fa013ca8990a82bdc60a88207b9384b30a003dc/packages/jbrowse-plugin-apollo/src/LinearApolloDisplay/components/LinearApolloDisplay.tsx#L85-L87

**Comment by dariober** [comment]
Commit 67b20939660fa28 has some code for showing the tooltip. It looks like this:

![image](https://github.com/GMOD/Apollo3/assets/6883382/fdc3b277-31e9-4afd-9b97-42e6ec218cc7)

At the moment, all warnings appear or disappear when clicking on any of them, which is probably messy. Also, labels overlap.
