### ISSUE TITLE
Add GFF3 to collaboration server from UI

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#31]
This is a stretch goad for the initial demo.

- Add an endpoint to check whether there is a GFF3 already on the collaboration server (for now, check cache)
- If there is not, the UI prompts for a GFF3 to upload
- Add endpoint to upload GFF3 to collaboration server which is then loaded into memory
- UI then allows the user to continue

**Comment by kyostiebi** [comment]
The following endpoints are implemented
- An endpoint (/filehandling/checkcachekeys) to check whether there is a GFF3 already on the collaboration server (for now, check cache). 
- An endpoint (/filehandling/uploadtocache) to upload GFF3 to collaboration server which is then loaded into memory

**Comment by garrettjstevens** [comment]
Superseded by #105
