### ISSUE TITLE
Add test data to staging instance

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#313]
The first step will be to add the assemblies and annotations through the Apollo menu in the UI. Then when adding the evidence tracks (e.g. CRAM, PAF), you'll add them to the config.json.

When adding the evidence tracks, if you use the JBrowse CLI tool, you'll have to do a bit of manual editing of the config.json, too. The CLI tool expects the assembly to be in the config.json, but Apollo assemblies are not stored there, they're created at runtime. So there are two options I can see:

Add a temporary assembly to the config.json so you can add the tracks, then delete the assembly from the config.json

or

Make a temporary config.json with the assemblies and tracks, then copy just the tracks portion over to the permanent config.json.

You'll need to use the Apollo ID for the assembly as the assembly name when adding the tracks. You can see this ID as the default name for a LGV opened of that assembly (e.g. "65260673cb86262b5111c80e" below).

![image](https://github.com/GMOD/Apollo3/assets/25592344/6a61675b-7e79-4e1b-bd08-f1df82412eb2)

**Comment by dariober** [comment]
The demo data is now accessible on https://apollo-staging.jbrowse.org/demo. It has annotation, cram, bigwig, and synteny files for *Plasmodium chabaudi* and *P. falciparum*. 

I noticed that despite the `TypeError: Failed to fetch` when loading the gff's, the annotation is anyway fully loaded (or so it seems to me...)
