### ISSUE TITLE
Shortcut to most recent bookmark does not work

### ISSUE THREAD

**Issue by dariober** [GMOD/Apollo3#333]
In the screenshot below, `Ctrl+Shift+M` should navigate to the most recently created bookmark but it has no effect. 

![image](https://github.com/GMOD/Apollo3/assets/6883382/730bf6ab-84ad-4d45-9cf1-2851e79f70c8)

**Comment by nick2432** [comment]
Can I contribute to this issue? I'm new here, but I have experience contributing to many other organizations. Is there a Discord channel or any other channel where I can discuss and get assistance?

**Comment by garrettjstevens** [comment]
Hi @nick2432, I forgot to mark this as fixed in in https://github.com/GMOD/jbrowse-components/pull/4003, but thanks!
