### ISSUE TITLE
Bug: Assembly not deleted from JBrowse when it's deleted from Apollo

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#334]
Noted by @kyostiebi:
> After deleting assembly from UI the deleted assembly is still shown in the drop-down menus (until session is cleared from browser address and relogin)

I think if we change `removeAssembly` to `removeSessionAssembly` in `DeleteAssemblyChange.ts`, it will fix this, but it needs testing.

We also need to test what happens if a track for an assembly is open when that assembly is deleted.

**Comment by kyostiebi** [comment]
Fixed
