### ISSUE TITLE
Bug: Click and drag of gene glyph doesn't work when there are UTRs along with exons in CanonicalGeneGlyph

### ISSUE THREAD

**Issue by shashankbrgowda** [GMOD/Apollo3#338]
Click and drag of gene glyph doesn't work when there are UTRs along with exons in CanonicalGeneGlyph

UTRs doesn't exist in canonical gene in this spec - https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md#the-canonical-gene

**Comment by garrettjstevens** [comment]
Imported GFF3s are now regularized (in #412), so this is not longer an issue.
