### ISSUE TITLE
Edit single feature in widget

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#339]
From Havana, it would be desirable to edit feature attributes while interacting with evidence tracks. We could do this by creating a feature editing widget that can be opened to edit a single feature, and since it is on the side, users can still interact with the tracks.

**Comment by garrettjstevens** [comment]
In `packages/jbrowse-plugin-apollo/src/index.ts` in the `install` method, add a WidgetType for Apollo feature details, something like this:
```ts
pluginManager.addWidgetType(
  () =>
    new WidgetType({
      name: 'ApolloFeatureDetails',
      heading: 'Apollo feature details',
      configSchema: ConfigurationSchema('ApolloFeatureDetailsWidget', {}),
      stateModel: stateModelFactory(pluginManager),
      ReactComponent: ApolloFeatureDetails,
    }),
)
```

The code for the widget can go in a new folder called `packages/jbrowse-plugin-apollo/src/FeatureDetailsWidget`.

Need to factor the feature attribute editing panel out from `packages/jbrowse-plugin-apollo/src/components/ModifyFeatureAttribute.tsx` and use the same panel in both that dialog and the ApolloFeatureDetails widget React component.

This widget will get shown when a user right-clicks on a feature and selects a "Edit feature details" menu item.

Here's an example of how to show a widget from a menu:
```js
{
  label: 'Edit feature details',
  icon: EditIcon,
  onClick: () => {
    if (self.session) {
      self.session.showWidget(
        self.session.addWidget(
          'ApolloFeatureDetails',
          'ApolloFeatureDetails',
          { feature: sourceFeature },
        ),
      )
    }
  },
}
```

The model will look something like
```js
export types
  .model('ApolloFeatureDetails', {
    feature: types.safeReference(AnnotationFeature),
  })
```

The React component will get a prop called `model` that is a mobx-state-tree model and will have the reference to the feature.

```js
export const ApolloFeatureDetails = observer(function (props: {
  model: IAnyStateTreeNode
}) {
  const { model } = props
  const { feature } = model
  // rendering code here
})
```

**Comment by kyostiebi** [comment]
There are also other wishes from Havana like:
- user should be able to select and edit multiple features at one go
- if user has selected CDS then all exons should be shown
