### ISSUE TITLE
Add CLI command to get and put JBrowse config files in collaboration server

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#433]
Add a command
```
apollo jbrowse get-config > config.json
```
and a command
```
apollo jbrowse set-config ./config.json
```

Then users can do things like:
```
apollo jbrowse get-config > config.json
jbrowse add-track ....... # get assembly id from above config.json
apollo jbrowse set-config ./config.json # This uses the ImportJBrowseConfigChange
```

**Comment by garrettjstevens** [comment]
The endpoint to get the config from is `jbrowse/config.json` (from `packages/apollo-collaboration-server/src/jbrowse/jbrowse.controller.ts`)

**Comment by dariober** [comment]
Thanks for feedback, @alpapan!

> (and i'd buy you a craft beer when you come to sydney if --profile to come right after apollo, that way i can do an alias apollo='apollo --profile shamiza_root' instead of having to copy paste each time)

We thought about moving some options to the `apollo` top command but it wasn't easy or possible (see https://github.com/oclif/core/discussions/954). However, you can use the the environment variable `APOLLO_PROFILE` to set the name of the default profile. For example (see also test [Apollo profile env](https://github.com/GMOD/Apollo3/blob/536c2b8ad83fd12d3efe1639992f15f60c386d76/packages/apollo-cli/src/test/test.ts#L1134)):

```
# On terminal or add to ~/.bashrc
export APOLLO_PROFILE=shamiza_root

# Now 
apollo user get
# is the same as
apollo user get --profile shamiza_root
```
