### ISSUE TITLE
BUG: "Add child feature" autocomplete not working, submit button is disabled

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#453]
Reported by EBI testers, the "Add child feature" feature type autocomplete is not working, and the submit button is disabled.

I think the likely culprit is that the ontology has not loaded correctly, but if that is the case we still need to:
- Indicate in the UI why the autocomplete isn't working
- Allow overriding the autocomplete with manual entry and submit

**Comment by garrettjstevens** [comment]
A bit more info on how this might be done. In the `OntologyTermAutocomplete`, it uses the passed-in `ontologyName` to load the correct `ontologyStore`. If the store can't be found, the autocomplete could show an additional message saying something along the lines of ``` `The '${ontologyName}' could not be found, suggestions are not available.` ``` 

https://github.com/GMOD/Apollo3/blob/89ccf49549f3bd640f6470e170da5048f3815988/packages/jbrowse-plugin-apollo/src/components/OntologyTermAutocomplete.tsx#L60-L63

**Comment by garrettjstevens** [comment]
After discussion today, we've decided that since #452 is going to make the feature type ontology (by default Sequence Ontology) an even more important part of our code, instead of the above approach we are going to not even display the Apollo track at all if there isn't a feature type ontology loaded. Instead we'll display a message saying that it needs a feature type ontology to run, which means users won't even be able to get to the autocomplete unless an ontology is loaded.

**Comment by dariober** [comment]
This below is what happens when trying to open an annotation track without sequence ontology. Message is a little basic just now...

![image](https://github.com/user-attachments/assets/5c2c7ddc-a7bb-42c5-b71b-b0a425510890)
