### ISSUE TITLE
provide a sequence track that shows stop codons when zoomed out and sequences (similar to Apollo's sequence track) when zoomed in

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo3#5]
The top-track is cut off, but there are both positive (cut off above) and negative strands here. 

This probably needs to be collapsible, as well (current JBrowse / Apollo interface).  

The top track is the zoomed out and the bottom track is zoomed in.  The black boxes in the top-track are the stop codons. 

![Example1b](https://user-images.githubusercontent.com/751274/106318374-b9c56c00-6224-11eb-8842-997ca15f493e.png)

Related to https://github.com/GMOD/Apollo3Server/issues/76 (and this may fix that).

**Comment by garrettjstevens** [comment]
Done in #341
