### ISSUE TITLE
Add basic user management

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#56]
Recording some of our discussion from our meeting today for future reference.

By default Apollo will rely on an off-the-shelf user management system, and so will not have any built-in user management UI. Whatever system is used will be provided to the Apollo Docker image, either within the Dockerfile or as a separate image to be used with `docker-compose`.

This user management system could be an LDAP server with an LDAP UI like [web2ldap](https://www.web2ldap.de/web2ldap.html) or [phpLDAPadmin](http://phpldapadmin.sourceforge.net/wiki/index.php/Main_Page). It could also be something like [Keycloak](https://www.keycloak.org/).

While adding this, we'll need to keep in mind that it will need to be able to be swapped out for e.g. using an org's LDAP directly.

**Comment by shashankbrgowda** [comment]
Hi @garrettjstevens, Can external people contribute to this project ? If so, can I work on this feature ?

**Comment by garrettjstevens** [comment]
@shashankbrgowda it could be possible, could you send me an email (my email address is on my GitHub profile) with a bit more info on why you'd like to work on this feature?

**Comment by garrettjstevens** [comment]
Done in #159
