### ISSUE TITLE
provide linked sequence tracks that can represent different zoom levels

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo3#6]
By clicking on objects, both tracks will automatically zoom to the same location at that zoom level

- not sure we want to do this, but useful placeholder

**Comment by nathandunn** [comment]
Dependent on #5  which provides a zoomed out track.  In this case the tracks are zoomed out:

![Example1b](https://user-images.githubusercontent.com/751274/106318758-39ebd180-6225-11eb-974e-7febd97b0bda.png)

**Comment by garrettjstevens** [comment]
Done (I think) in #341
