### ISSUE TITLE
Add files module/controller/service

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#79]
From discussion with @rbuels, add an endpoint for managing files, specifically at first a way to upload files. The user will supply a file and it will be saved to disk and the following information will be saved in MongoDB:
```ts
type File { checksum: number; basename: string; type: 'text/x-gff3' | 'text/x-fasta' }
```
For example:
```ts
{ checksum: 12453446236435, basename: 'mygenome.fasta', type: 'text/x-fasta' }
```
The file will be saved in a compressed format. The idea is that once a file is uploaded successfully, it can be referenced in change objects, perhaps looking something like this:
```ts
{ type: 'AddReferenceSequencesFromFile', fileChecksum: 12453446236435 }
```

**Comment by garrettjstevens** [comment]
xref https://github.com/GMOD/jbrowse-plugin-apollo/issues/65

**Comment by garrettjstevens** [comment]
This will need a new endpoint "files," which to match the other modules can be created by running `yarn dlx @nestjs/cli generate resource files` in the `packages/apollo-collaboration-server/` directory.

This will also need a MongoDB schema that has:

```ts
interface File {
  basename: string // the name of the file that was uploaded
  checksum: number // or string, depending on hash used
  type: 'text/x-gff3' | 'text/x-fasta' // depends on what kind of file was uploaded
}
```

There will be `/files/fasta` and `/files/gff3` endpoints. Users can POST a new file to those endpoints, GET a list of files, and GET a file with e.g. `/files/fasta/507f1f77bcf86cd799439011`.

The location the files are saved to should be configurable in the ENV file. The file name that it is saved as internally should be the file ID, e.g. `507f1f77bcf86cd799439011`, not the file name of the uploaded file..

**Comment by kyostiebi** [comment]
When we upload and compress user file, should we also add timestamp or userstamp to compressed filename? One or more user may use same filenames and those may get mixed up.

**Comment by rbuels** [comment]
One thing to clarify about this is that if the same file is uploaded multiple times (possibly with different names) it is only stored once, because it’s stored name is a hash of its contents.

**Comment by garrettjstevens** [comment]
Good point, I forgot about that. So the file name should be the hash, not the (MongoDB) file ID. I'll correct that in my above comment.
